### ISSUE TITLE
jars on sonatype

### ISSUE THREAD

**Issue by daenenk** [ldaniels528/means-js#2]
Nice work.
I would like to see you jars on https://oss.sonatype.org/content/groups/public/com/github/
rather than having to build them locally.

**Comment by ksberg** [comment]
ditto: from build instructions ... sbt.ResolveException: unresolved dependency: com.github.ldaniels528#scalajs-common_sjs0.6_2.11;0.2.0: not found

**Comment by daenenk** [comment]
Had the seem experience. When you first build locally as in the build instructions and then use 
`libraryDependencies += "com.github.ldaniels528" %%% "scalajs-nodejs-express" % "0.2.1"` i.s.o. `0.2.0` in your own build.sbt file, it will work. Still it would be better if we would not have to build it locally and just fetch the jar from sonatype.

**Comment by ldaniels528** [comment]
Just add the following to your build.sbt:

resolvers += "releases" at "https://oss.sonatype.org/service/local/staging/deploy/maven2"

**Comment by ldaniels528** [comment]
BTW, I just released v0.2.1, which contains quite a few fixes.

**Comment by Voltir** [comment]
I have that resolver on my path and it still fails to fetch - and normally I just go look at the various urls to figure out what I might have missed, but in this case I get an authentication error when trying to browse directly to, eg: https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/ldaniels528/scalajs-nodejs-crypto_sjs0.6_2.11/

Also, that url looks a little funny to me, having the release on /local/staging seems not quite right..

**Comment by ldaniels528** [comment]
I'm pretty new to the concept of publishing resources; however, I just tested the latest release myself (0.2.2.2) using the resolver below, and it works perfectly.

resolvers += "releases" at "https://oss.sonatype.org/service/local/staging/deploy/maven2"

**Comment by sjrd** [comment]
Staging releases disappear after some time. You should _release_ your staging repo (e.g. from the OSS "Nexus" interface) so that they are consolidated as Maven artifacts on Maven Central, and do not disappear.

**Comment by ldaniels528** [comment]
I'm logged into oss.sonatype.org, but I'm having trouble figuring out how to promote my code to release... I've reach out to their support staff for help. I'll keep you guys posted.

**Comment by sjrd** [comment]
@ldaniels528 This should explain it all: http://central.sonatype.org/pages/releasing-the-deployment.html

**Comment by ldaniels528** [comment]
Version 0.2.3.1 has been publicly released via Sonatype.
